apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: activemq-artemis-operator-source
  namespace: operators
spec:
  displayName: ActiveMQ Artemis Operators
  image: quay.io/arkmq-org/activemq-artemis-operator-catalog:v2.0.2
  sourceType: grpc
