apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  deploymentPlan:
    size: 1
    image: placeholder
  acceptors:
  - name: mqtt
    port: 1883
    protocols: MQTT
