schema: olm.template.basic
entries:
  - schema: olm.package
    name: activemq-artemis-operator
    defaultChannel: upstream
  - schema: olm.channel
    package: activemq-artemis-operator
    name: upstream
    entries: []