# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/broker.amq.io_activemqartemises.yaml
- bases/broker.amq.io_activemqartemisaddresses.yaml
- bases/broker.amq.io_activemqartemisscaledowns.yaml
- bases/broker.amq.io_activemqartemissecurities.yaml
#+kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
